"""GitHub の公開リポジトリと works.db を比較して未登録リポジトリを一覧化"""

import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).parent / "works.db"

# GitHub repos (全12ページから取得)
github_repos = {
    "Kazuhito00", "python-qrcode-synthetic-benchmark", "onnx-cv-graph",
    "onnx-cv-graph-node-editor", "Display-Corner-Estimation-Prototype",
    "Multimodal-Node-Editor", "presentation-2026", "litellm-ledger",
    "Gemini-2.5-API-Object-Detection-Colaboratory-Sample", "ndlocr-lite",
    "MiniCPM-V4.5-Colaboratory-Sample", "movie2jpg", "Retinexformer-ONNX-Sample",
    "PaddleOCRv5-ONNX-Sample", "Audio-Processing-Node-Editor",
    "Image-Processing-Node-Editor", "mediapipe-python-sample",
    "github-profile-trophy", "ipne-json2demo",
    "DEIMv2-Colaboratory-Training-Sample", "DEIMv2-ONNX-Sample",
    "Qwen3-VL-Colaboratory-Sample", "Sarashina2.2-Vision-Colaboratory-Sample",
    "PINTO_model_zoo-Gradio-Demo", "PINTO_model_zoo", "barfi",
    "Pycon-mini-Tokai-2025-PyScript-OpenCV", "presentation-2025",
    "DualImagePNG-for-X", "LiSenNet-ONNX", "STFT-ISTFT-ONNX",
    "GTCRN-ONNX-RealTime-Inference-Sample", "VoiceFixer-ONNX",
    "Awesome-Nano-Banana-images", "PaddleOCRv3-ONNX-Sample", "MaAI",
    "LFM2-VL-Colaboratory-Sample", "SmolVLM2-Colaboratory-Sample",
    "OpenAI-chat-api-simple-Colaboratory-Sample",
    "Qiita-AdventCalendar-20241217-OpenCV", "Overlay-Audio-Spectrum-Using-OpenCV",
    "Draw-Audio-Spectrum-Using-OpenCV", "APNE-Input-ReSpeaker-v2-Node",
    "APNE-Input-getUserMedia-Mic-Node", "Voxtral-Mini-3B-Colaboratory-Sample",
    "Pyxel-EscapeSweeper", "IPNE-YouTube-Input-Node", "pygame-hexagonal2048",
    "Pyxel-HexMinesSweeper", "GLM-4.1V-9B-Thinking-Colaboratory-Sample",
    "FastVLM-Colaboratory-Sample", "Chaquopy-OpenCV-Camera-Sample",
    "Google-Colab-Julia", "alltracker-Colaboratory-Sample", "OnnxOCR",
    "Kimi-VL-Colaboratory-Sample", "PlateYOLO-JP-Prototype",
    "Heron-NVILA-Colaboratory-Sample", "cv_rotate_3d", "Silero-VAD-ONNX-Sample",
    "pyxel-pymunk-web-test", "LightGlue-ONNX",
    "DEIM-Colaboratory-Training-Sample", "D-FINE-Colaboratory-Training-Sample",
    "RT-DETR-Colaboratory-Training-Sample", "Sarashina2-Vision-Colaboratory-Sample",
    "qrcode-pose-estimation", "DEIM-ONNX-Sample", "Qwen2.5-VL-Colaboratory-Sample",
    "Ovis2-Colaboratory-Sample", "Asagi-VLM-Colaboratory-Sample", "Pyxel_Web_Test",
    "Qiita-AdventCalendar-20241214-Pyxel", "ita-corpus",
    "Ivy-VL-Colaboratory-Sample", "InternVL-Colaboratory-Sample",
    "Qiita-AdventCalendar-20241210-OpenCV", "presentation-2024",
    "Pycon-mini-Tokai-2024-VLM-Colaboratory-Sample", "D-FINE-ONNX-Sample",
    "Janus-1.3B-Colaboratory-Sample", "RT-DETR-ONNX-Sample",
    "Skin-Clothes-Hair-Segmentation-using-SMP", "Phantom-Colaboratory-Sample",
    "Molmo-Colaboratory-Sample", "Phi3.5-Vision-Colaboratory-Sample", "GeoCalib",
    "ONNX-SAM2-Segment-Anything", "MOT-Tracking-by-Detection-Pipeline",
    "Anime-Segmentation-ONNX-Colaboratory-Sample", "SegGPT-Colaboratory-Sample",
    "CartoonSegmentationOnnx-Colaboratory-Sample", "CoLIE-Colaboratory-Sample",
    "White-box-Cartoonization-Colaboratory-Sample", "Qwen2-VL-Colaboratory-Sample",
    "albumentations-examples", "cloths_segmentation-onnx-sample",
    "Florence-2-Colaboratory-Sample", "ONNX-YOLOv9-MIT-ObjectDetection",
    "MiniCPM-V2.6-Colaboratory-Sample", "mario-ai-challenge",
    "MobileVLM-V2-Colaboratory-Sample", "nsfw_model_onnx_sample",
    "MVANet-ONNX-Sample", "BiRefNet-ONNX-Sample",
    "OpenVINO-Colab-Inference-Sample-using-various-frameworks-weights",
    "MPCount-ONNX-Sample", "SAM2-Colaboratory-Sample", "csp-psd-image-viewer",
    "clip_studio_paint_tool", "yolox-bytetrack-mcmot-sample",
    "XFeat-Image-Matching-ONNX-Sample", "ServiceLogos", "LYT-Net-ONNX-Sample",
    "MeshFlow-Colaboratory-Sample", "GlobalFlowNet-Colaboratory-Sample",
    "VidStab-Compare-Sample", "EfficientSAM-ONNX-Sample",
    "MobileSAM-ONNX-Sample", "Segment-Anything-Model-ONNX-Sample",
    "YOLO-World-v2-Colaboratory-Gradio-Demo",
    "ONNX-YOLO-World-Open-Vocabulary-Object-Detection",
    "OpenCV-Object-Tracker-Python-Sample", "convert_coco_to_voc",
    "vehicle-reid-0001-onnx-sample", "presentation-2023", "openlenda",
    "Detection-PoseEstimation-Pipeline", "openlenda-onnx-inference-sample",
    "tPLCnet", "NARUTO-HandSignDetection", "YOLOPv2-ONNX-Sample", "cvpr",
    "MusicGen-colab", "YOLOX-Colaboratory-Training-Sample",
    "YOLOX-ONNX-TFLite-Sample", "LDC-ONNX-Sample", "simple-annotation-on-colab",
    "LDC-Skeletonize-Sample", "Lite-Mono-ONNX-Sample", "FLW-Net-onnx2tf-sample",
    "segment-anything", "hand-keypoint-classification-model-zoo",
    "hand-gesture-recognition-using-mediapipe", "the-algorithm",
    "Multi-Otsu-Thresholding-Sample", "DIS-ONNX-Sample", "SCI-ONNX-Sample",
    "yolox-bytetrack-sample", "M5Stack-Door-Plate", "Bread-ONNX-Sample",
    "DAMO-YOLO-Colaboratory-Training-Sample", "FreeYOLO-ONNX-Sample",
    "DAMO-YOLO-ONNX-Sample", "sahi-yolox-onnx-sample", "convert_voc_to_coco",
    "OpenCV-Mesh-Deformation", "Informative-Drawings-ONNX-Sample",
    "MoveNet-Python-Example", "royalty-free-360-degree-images", "stable-diffusion",
    "cv_overlay_inset_image", "nanodet", "NanoDet-Colaboratory-Training-Sample",
    "NanoDet-ONNX-Sample", "ByteTrack-ONNX-Sample",
    "omnidirectional-viewer-sample-using-opencv", "pafy", "presentation-2022",
    "OpenCV-QRCodeDetector-Sample", "Person-Detection-using-RaspberryPi-CPU",
    "convert_image_compression", "NARUTO-Sharingan-Iris-Overlay",
    "micropython-micro-gui", "onnx-model-encrypt-sample",
    "YOLOX-Colaboratory-coco-minitrain", "ObjectDetection2VOC",
    "mediapipe-sface-sample", "sahi", "yolox-motpy-sample",
    "Object-Detection-API-TensorFlow2ONNX", "PeopleSansPeople",
    "landmarks-classifier-asia-onnx-sample", "NGK2022S-LT", "imread_from_url",
    "japanese-rust-companies", "YOLOP-ONNX-Video-Inference-Sample",
    "NTIRE-2021-Dehazing-Two-branch-Colaboratory-Sample",
    "Traffic-Sign-Detection-ONNX-Sample", "YOLOX", "cheatsheets",
    "MonocularDepthEstimator-Simple-Calibration",
    "Zenn-Book-S3-SageMaker-S3-Sample", "GrabCut-Annotation-Tool",
    "open_nsfw_onnx_sample", "FaceDetection-Anti-Spoof-Demo",
    "LearningToCountEverything-Colaboratory-Sample",
    "TFLite-ModelMaker-EfficientDet-Colab-Hands-On", "inappropriate-words-ja",
    "models", "U-2-Net-ONNX-Sample", "BASNet-ONNX-Sample",
    "Tensorflow2-ObjectDetectionAPI-Colab-Hands-On",
    "PyCon-mini-Shizuoka-2021-Talk4", "DM-Count-ONNX-Sample",
    "ONNX-LSTR-Lane-Detection", "presentation-2021",
    "YuNet-ONNX-TFLite-Sample", "7segment-display-reader",
    "AnimeGANv2-ONNX-Sample", "AnimeGANv2-Face-Overlay-Demo",
    "piano_transcription_inference", "kalidokit",
    "JINS-MEME-Python-WebSocketServer-Sample", "depthai-ros",
    "iris-detection-using-py-mediapipe", "Tokyo2020-Pictogram-using-MediaPipe",
    "AprilTag-Detection-Python-Sample", "cvoverlayimg",
    "Mobile-Object-Localizer-Sample", "voc2coco",
    "TensorFlow-Similarity-MNIST-Sample", "OpenCV-CameraCalibration-Example",
    "mnist-sample-using-tf-simple-metric-learning",
    "built-onnxruntime-for-raspberrypi-linux", "tensorflow2-keras-learn",
    "deep_running", "Qiita-AdventCalendar-20201212-OpenCV",
    "Single-Hand-Localization", "7seg-image-generator-for-Axross",
    "OpenCV-img_hash-Sample", "L-Image-Maker", "WindowUtilFor360WebCam",
    "generate-1characters-qr", "amzqr4lambda", "Unity-Barracuda-Objectron-WebGL",
    "M-LSD-warpPerspective-Example", "mlsd", "MVTec-Anomaly-Detection",
    "click-warpPolar", "image-capture-class-annotation", "7seg-image-generator",
    "Anime-Semantic-Segmentation-GAN", "pyboy-gbdk-examples",
    "tf-keras-applications-cifar10-example", "RO-GAN-using-Lightweight-GAN",
    "SPADE-pix2pix-for-Anime", "PlantUML-ColorSet-Example", "FingerFrameLens",
    "Unity-Presentation-using-DOTween", "mouseselect-screenshot-windows",
    "GrabCut-Tool", "NeuralNetworkConsole-MNIST-Sample",
    "NeuralNetworkConsole-Titanic-Sample",
    "Unity-Barracuda-SingleHandLocalization-WebGL", "Unity-SpellRestoration",
    "simple-virtual-mouse-using-mediapipe",
    "Unity-Barracuda-Reversi-WebGL-Sample", "FaceDetection-Image-Overlay",
    "awesome-mediapipe", "Unity-MediaPipeJs-SendMessage-WebGL-Sample",
    "UltraFaceBarracuda", "Unity-Barracuda-TinyYoloV2-WebGL-Sample", "yolo2_onnx",
    "Unity-Barracuda-MobileNet-WebGL-Sample", "Unity-VideoPlayer-WebGL-Sample",
    "Unity-Barracuda-MNIST-WebGL-Sample", "opencv_3rdparty",
    "Unity-MousePaint-WebGL-Sample", "Unity-WebCamTexture-WebGL-Sample",
    "XDoG-OpenCV-Sample", "color-equalize-hist-sample", "hsv-mask-extracter",
    "presentation-2020", "yolov4_crowdhuman", "object-detection-bbox-art",
    "Polygon-Filter", "hakone-ekiden", "javascript-sensor", "UniverseNet",
    "Yet-Another-Anime-Segmenter", "handsfree", "cv-comparison-slider-window",
    "cv-picture-in-picture-window", "Kuwahara-Filter", "SendGrid-Colaboratory",
    "SkyAR", "Python", "FingerFrameDetection-TF2", "image-mask-replace",
    "diagrams", "tf-lite-unity-sample", "PyCaret-Learn", "epic-spinners",
    "tf-simple-metric-learning", "tensorflow-yolov4-tflite", "DanbooRegion",
    "Weighted-Boxes-Fusion", "cv-warpPolar-example", "pyod",
    "click-warp-perspective", "awesome-machine-learning",
    "tf2-keras-explain-examples", "kaggle-memo", "tfrecord-viewer",
    "EfficientDet", "nlpaug-examples", "cutmix", "mixup",
    "ImageDataGenerator-examples", "Jupyter-VideoCapture-Demo",
    "Unity-Quad-Shader-Learn", "YOLO-UnityBarracuda", "webCamGoogleColab",
    "makers-coc", "White-box-Cartoonization", "3d-photo-inpainting",
    "presentation-2019", "OpenCV-readNetFromTensorflow-sample",
    "hand-detection-2class-MobilenetV1-SSD",
    "hand-detection-3class-MobilenetV2-SSDLite", "cvfpscalc",
    "object-detection-react", "SuperGluePretrainedNetwork",
    "cvui-py-two-knob-trackbar", "desktopdraw-use-dxlib",
    "opencv2webslides-sample", "opencv2eel-sample", "cvdrawtext",
    "object-detection-python", "learn_aug_for_object_detection.numpy",
    "object-detection-ios", "object-detection-android", "jupyter-rise", "guiflow",
}

conn = sqlite3.connect(DB_PATH)
db_repos = set(
    r[0] for r in conn.execute(
        "SELECT repo_name FROM works WHERE repo_name IS NOT NULL"
    ).fetchall()
)

missing = sorted(github_repos - db_repos)
print(f"GitHub repos: {len(github_repos)}")
print(f"DB repos:     {len(db_repos)}")
print(f"未登録:       {len(missing)}")
print()
for r in missing:
    print(f"  https://github.com/Kazuhito00/{r}")
